# Generated by Django 5.0.1 on 2024-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('images', models.ImageField(upload_to='slides/')),
                ('tagline', models.CharField(max_length=100)),
            ],
        ),
    ]
