# Generated by Django 5.0.1 on 2024-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='tagline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
