# Generated by Django 5.0.1 on 2024-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_alter_slider_description_alter_slider_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
